### ISSUE TITLE
Early exit during fuzzing

### ISSUE THREAD

**Issue by guyf2010** [MCUSec/uEmu#11]
With some binaries after several hours of execution uEmu will abort. 

The output in the uEmu window after this occurs:
qemu: fatal: Trying to execute code outside RAM or ROM at \<address\>
\<register dump\>
./launch-uEmu.sh: line 83:  5716 Aborted                 LD_PRELOAD=$LIBS2E $QEMU -k en-us $GRAPHICS -M mps2-ans2e -cpu cortex-m3 -m $QEMU_MEMORY -enable-kvm -serial file:s2e-last/serial.txt $QEMU_EXTRA_FLAGS -kernel $FIRMWARE

I would've expected this to be reported as a crash in AFL, not for uEmu to exit.

I ran this using the Vagrant image. Please let me know if there's any information I can provide to debug this further, or if this is an issue on my end.

**Comment by weizhou-chaojixx** [comment]
Which firmware you meet such problem？ I will try to reproduce your problem.

**Comment by guyf2010** [comment]
I had encountered this issue with the RF Door Lock firmware, and a modified version of the gateway binary.

**Comment by weizhou-chaojixx** [comment]
Sorry for the delay, after running more fuzz testing trials, I encounter your issue in RF door Lock firmware. I found that is because the overflow point address (e.g., 0x45678912) just falls into the peripheral address from 0x40000000- 0x60000000. When accessing such an address, uEmu will mistakenly consider it as a new peripheral.  I have added the option 'allow_new_phs', if no new peripheral will be accessed (all peripherals are covered in KB file) during fuzzing phase, you can disable it. I have also disabled this option and updated the configuration file of this firmware(https://github.com/MCUSec/uEmu-real_world_firmware/commit/9d389790f0332208f03c67108febafa49b3d3ebd#diff-381a9a0cd6ca57fb85ef0cb9ff1e508f7d95b94441b03a9c3671043eac9d531dR47). You are free to re-run it and if you have further questions, please let me know.
