### ISSUE TITLE
AFL enter "should not be here"

### ISSUE THREAD

**Issue by spencerwuwu** [MCUSec/uEmu#15]
Hi uEmu authors,

I am using the vagrant built vm on a debain 10 system. I followed the instructions in the README and try to fuzz [XML_Parser.elf](https://github.com/MCUSec/uEmu-real_world_firmware/blob/pre-publication/XML_Parser.elf) with [small_document.xml](https://github.com/MCUSec/uEmu-real_world_firmware/blob/pre-publication/small_document.xml).

The commands I ran are as below:
```
$ cd /vagrant
$ python3 uEmu-helper.py ~/uemu/uEmu-real_world_firmware/XML_Parser.elf ~/uemu/uEmu-real_world_firmware/XML_Parser.cfg
$ ./launch-uEmu.sh
$ python3 uEmu-helper.py ~/uemu/uEmu-real_world_firmware/XML_Parser.elf ~/uemu/uEmu-real_world_firmware/XML_Parser.cfg -kb s2e-last/XML_Parser.elf-round1-state51-tbnum1063_KB.dat -s ~/uemu/uEmu-real_world_firmware/small_document.xml
$ ./launch-AFL.sh
```
From here I can only see the fuzzer keep printing `##################################should not be here`.

Do you possibly know what could be the cause of it? I tried a few other ones and they were all about the same.
Thank you in advance!

**Comment by weizhou-chaojixx** [comment]
Hi, actually, you can ignore such warnings. Since we use share memory to sync AFL bitmap between AFL and uEmu engine, sometimes AFL has to wait for a while to ensure uEmu has finished the bitmap update. I just add such warning to record how often AFL needs to wait for uEmu one round fuzzing execution. I will remove such misunderstanding warning information.
